### ISSUE TITLE
0.5.0 Julia is broken

### ISSUE THREAD

**Issue by sshanshans** [JuliaCloud/JuliaBox#422]
Hello,

I tried to open 0.5.0 dev in JuliaBox, but the kernel is dead. Could somebody help look at this issue?

Thank you so much for your help!
Shan Shan

**Comment by ViralBShah** [comment]
Best to wait for the release. We are unlikely to address this for now since the release is so near.

**Comment by stevengj** [comment]
This can be closed... 0.5 has been released and working on JuliaBox for a long time now.
