### ISSUE TITLE
Replace 0.5.0-rc4 with the 0.5.0 release

### ISSUE THREAD

**Issue by ararslan** [JuliaCloud/JuliaBox#456]
Currently the only available 0.5-series version on JuliaBox is 0.5.0-rc4. But since 0.5.0 has been officially released, it would be great if JuliaBox could use that instead.

I assume this is already being worked on, I just figured it'd be nice to have an issue to close once that's done. 😉

**Comment by nkottary** [comment]
This is done.

**Comment by ararslan** [comment]
Awesome, thanks @nkottary!
