### ISSUE TITLE
Restoring tutorial folder on login causes unexpected symlink issues

### ISSUE THREAD

**Issue by felixrehren** [JuliaCloud/JuliaBox#482]
The steps
1. Rename the "tutorial" folder, to, e.g., "tutorial2"
2. Log out, log back in. The "tutorial" folder is restored, "tutorial2" still exists

Cause the following unexpected behaviour:
- Changing files in the folder "tutorial2" changes them in the folder "tutorial"
- It is not possible to delete "tutorial2",  giving an error `... OSError: Cannot call rmtree on a symbolic link`

Both issues seem to be caused by a symbolic link between the folders

**Comment by aviks** [comment]
This is an artefact of how the docker filesystems are constructed. Please don't move or delete the `tutorial` folder.
