### ISSUE TITLE
WebSocket connection failed

### ISSUE THREAD

**Issue by ptoman** [JuliaCloud/JuliaBox#484]
JuliaBox starts Jupyter but cannot connect to the kernel.  It looks like a websocket problem (perhaps a kernel is being created with one identifier and the page is trying to talk to another identifier?)

Some variables that come to mind that have no effect: browser, incognito mode, login method (Github vs. LinkedIn), internet connection (VPNness), version of Julia/Python, whether notebook is existing or new.

As per #483 and #424, I tried moving ~/.julia to another name -- the problem persists.  I also tried the pretty yellow button "Reset my packages" within my Account, and I was told I'm already using system packages.

I am able to start julia and python in the Console.

In very weakly potentially relevant news, Juliabox worked fine for me until around the time I rm -rf'ed a lot of files from a completed project to clean up space on your graciously provided servers (I'd been checkpointing a ton for Mykel Kochenderfer's class, which is why I'm exploring JuliaBox).

<img width="956" alt="cogiaaakmohggenl" src="https://cloud.githubusercontent.com/assets/324410/19879843/82f3a070-9fb4-11e6-945b-436f463b98e0.png">

```
Session: kernel_created (f553843c-788e-4b87-a1d2-a52c882f514e)session.js:52:13
Starting WebSockets: wss://templ-prod-group-2hn2-templ-prod-group.juliabox.com./api/kernels/292fdf13-ecf8-4d15-93ac-1efed5ace7a2kernel.js:440:9
Firefox can’t establish a connection to the server at wss://templ-prod-group-2hn2-templ-prod-group.juliabox.com./api/kernels/292fdf13-ecf8-4d15-93ac-1efed5ace7a2/channels?session_id=95B1A6D2CDCC4F4EAF3E0724B19EA5EF.kernel.js:442:18
Kernel: kernel_disconnected (292fdf13-ecf8-4d15-93ac-1efed5ace7a2)kernel.js:98:13
WebSocket connection failed:  wss://templ-prod-group-2hn2-templ-prod-group.juliabox.com./api/kernels/292fdf13-ecf8-4d15-93ac-1efed5ace7a2kernel.js:525:13
Connection lost, reconnecting in 1 seconds.kernel.js:538:13
Kernel: kernel_reconnecting (292fdf13-ecf8-4d15-93ac-1efed5ace7a2)kernel.js:98:13
Starting WebSockets: wss://templ-prod-group-2hn2-templ-prod-group.juliabox.com./api/kernels/292fdf13-ecf8-4d15-93ac-1efed5ace7a2kernel.js:440:9
Firefox can’t establish a connection to the server at wss://templ-prod-group-2hn2-templ-prod-group.juliabox.com./api/kernels/292fdf13-ecf8-4d15-93ac-1efed5ace7a2/channels?session_id=95B1A6D2CDCC4F4EAF3E0724B19EA5EF.kernel.js:442:18
Kernel: kernel_disconnected (292fdf13-ecf8-4d15-93ac-1efed5ace7a2)kernel.js:98:13
WebSocket connection failed:  wss://templ-prod-group-2hn2-templ-prod-group.juliabox.com./api/kernels/292fdf13-ecf8-4d15-93ac-1efed5ace7a2kernel.js:525:13
Connection lost, reconnecting in 2 seconds.
```

**Comment by camaramm** [comment]
I have followed through the same as mentioned by @ptoman , and I also cannot connect to the kernel.

**Comment by nkottary** [comment]
I tried cleaning up my home directory to reproduce this error but I was still able to connect to the kernel. Apart from the 2 measures mentioned in #483 I don't have any other suggestions to fix this issue. Looks like there may be something in your network that is blocking websockets.

**Comment by camaramm** [comment]
My problem was browser's third-party cookies setting. It is working now.
