### ISSUE TITLE
Update the default Julia version in the console

### ISSUE THREAD

**Issue by ararslan** [JuliaCloud/JuliaBox#485]
It seems that currently only 0.4 is available from the console:
```
juser@juliabox:~$ which julia
/usr/bin/julia
juser@juliabox:~$ julia --version
julia version 0.4.7
```
It would be great if this could be updated to 0.5.

**Comment by tanmaykm** [comment]
I think you should find other Julia versions already installed at `/opt`.
Doesn't just setting `PATH` appropriately in `~/.bashrc` work?

**Comment by ararslan** [comment]
Aha, I didn't realize there were other versions in `/opt`. Thanks! Setting it as you suggest should work fine, I just figured it would be convenient for the default version in the console to be the most recent release.

**Comment by ararslan** [comment]
Looks like this has been addressed.
```
juser@juliabox:~$ julia --version
julia version 0.5.0
```
👍
