### ISSUE TITLE
Texlive no longer installed?

### ISSUE THREAD

**Issue by mykelk** [JuliaCloud/JuliaBox#486]
My students and I had been using Juliabox this quarter, but it looks like texlive is suddenly no longer included. From the notebook and console, I cann't run lualatex, latex, pdflatex, etc. Can this be brought back? It is required for BayesNets.jl, PGFPlots.jl, etc. which are dependencies for my classes.

**Comment by ViralBShah** [comment]
Cc @nkottary

**Comment by nkottary** [comment]
This is fixed now.
