### ISSUE TITLE
Make the 0.6.0-dev kernel use the actual Julia nightly

### ISSUE THREAD

**Issue by ararslan** [JuliaCloud/JuliaBox#489]
This was implemented over a year ago in #243 (and subsequently requested in #244) but it seems not to actually be using the _nightly_ build. For example, when I start a new Julia v0.6.0-dev notebook, `versioninfo()` tells me that it's using v0.6.0-dev.1230, which is actually 60(!) days old. It would be awesome if it could use the most recent nightly build.

**Comment by aviks** [comment]
moot now. thanks.

**Comment by ararslan** [comment]
Is this repo still used or has development of JuliaBox been taken "behind the scenes"?
