### ISSUE TITLE
Dead kernel for Julia 0.6.0-dev

### ISSUE THREAD

**Issue by felixrehren** [JuliaCloud/JuliaBox#490]
Yesterday and today, running any notebook on Julia 0.6.0-dev results in the immediate message

> **Kernel Restarting**
The kernel appears to have died. It will restart automatically.

> **Dead kernel**
The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened.

Restarting does not help. Julia 0.5.0 runs fine. Julia 0.6.0-dev was running ok on Friday I think.

**Comment by felixrehren** [comment]
Ping @tanmaykm @nkottary, problem persists

**Comment by tanmaykm** [comment]
Maybe be same as #424 and #483.
Could you try the suggestions in there?

**Comment by felixrehren** [comment]
So I guess that means it's a local problem :) then I'm not so worried about it for now
I tried resetting the packages, checked the cookie setting, and restarted my browser, without success. I'll keep playing around

It may be worth mentioning the package reset option in the Dead Kernel error message.

**Comment by tanmaykm** [comment]
It is broken for me too, it does not seem to be a local problem.
Needs to be investigated. Thanks for reporting.

**Comment by sc0ttwad3** [comment]
+1 for me.

**Comment by sbromberger** [comment]
This is affecting juliabox.com as well.

**Comment by nkottary** [comment]
Fixed.
