### ISSUE TITLE
python kernels

### ISSUE THREAD

**Issue by weymouth** [JuliaCloud/JuliaBox#491]
Please let me know if I've missed something. I used to be able to open and run python kernels using juliabox as well as IJulia kernels. Was this functionality removed or is this a bug?

Thanks

**Comment by stevengj** [comment]
I'm guessing the functionality was removed intentionally. I don't think there is enough funding to provide a free Python platform as well as Julia.

**Comment by stevengj** [comment]
Indeed, this was answered by @ViralBShah at https://groups.google.com/forum/#!topic/julia-box/pbyJ_WG5Lhc
