### ISSUE TITLE
JuliaBox 0.5.1 kernel dead error

### ISSUE THREAD

**Issue by selvaprabun** [JuliaCloud/JuliaBox#492]
Hello, My class and I have been using the 0.5.0 kernel on JuliaBox for optimization with JuMP. As of today morning, we are getting a kernel dead error when using 0.5.1 on JuliaBox and it will not restart. 

I just tried logging into JuliaBox from another google account where I hadn't used the 0.5.0 kernel and everything works fine on 0.5.1. So my guess is that the issue has something to do with the previous use of 0.5.0. 

Is there a way of cleaning out all the packages and starting fresh on the 0.5.1 kernel in a given google account? 

Thanks

**Comment by nkottary** [comment]
Dup of #424
