### ISSUE TITLE
Dead Kernel with new Julia 0.5.1 notebook

### ISSUE THREAD

**Issue by gdowdy3** [JuliaCloud/JuliaBox#494]
When I try to create a new Julia 0.5.1 notebook, I get an error message saying

> The kernel appears to have died. It will restart automatically.

Moments later, I get the longer error message:

> The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened.

The dialog box containing this message has two buttons: "Try restarting now" and "Don't restart".  If I click "Try restarting now", the kernel just dies again, leading me back to the same error message.

**Comment by gdowdy3** [comment]
I experienced the error on my PC, running Juliabox in Chrome.  My friend saw the same error on her Mac, running Juliabox in Firefox.

**Comment by gdowdy3** [comment]
Signing in and out of Juliabox does not fix the error.

**Comment by nkottary** [comment]
Try deleting your `~/.julia` as mentioned in #424

**Comment by gdowdy3** [comment]
That did the trick!  Thanks, @nkottary!

**Comment by gdowdy3** [comment]
To give a slightly more detailed solution for those who encounter this problem in the future, here's what I did:

1. Click on the little wrench in the top right corner of the JuliaBox window.

1. Scroll down to the bottom of the page and click on the "Reset my packages" button.

1. Click through the confirmation messages.
