### ISSUE TITLE
v0.6 issues?

### ISSUE THREAD

**Issue by jverzani** [JuliaCloud/JuliaBox#500]
Using juliabox with students in a classroom finds two things occurring the past few days:

* With v0.6 for the last few days it is not possible to get a stable kernel;even issuing `2+2` isn't working

* others get a stable kernel, but find their .julia has been changed. Here the package appear to be removed, but not the precompiled versions in .julia/lib This one seems quite odd, and hasn't been fully investigated.

Apologies if this is the wrong place to post this.

**Comment by aviks** [comment]
can you try deleting the user's `.julia` folders and trying again. This will remove all user installed packages, but will likely solve the instabilities. Things like this generally occur when the pre-built packages are updated.

**Comment by jverzani** [comment]
Thanks! That seems to work as a solution.
