### ISSUE TITLE
next.juliabox: Package build is successful but doesn't seem to do anything

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaCloud/JuliaBox#501]
I'm trying out the new next.juliabox.com interface, but the package build doesn't seem to work. Any advice?

**Comment by aviks** [comment]
What package are you trying to build? Any errors?

**Comment by dlfivefifty** [comment]
It said "Build Successful".  I had quite a few packages so I can try to narrow it down (I had assumed successful meant successful...)

**Comment by dlfivefifty** [comment]
Hmm, I guess it was a dud package. (I changed my Github email which started the workspace from scratch, so I don't remember which packages I had.)

**Comment by dlfivefifty** [comment]
With one extra package, it now works correctly.
