### ISSUE TITLE
All folders and notebooks lost after signing up at next.juliabox.com

### ISSUE THREAD

**Issue by yulin2017** [JuliaCloud/JuliaBox#502]
Hi,

I used the same google account to sign up for next.juliabox.com as juliabox.com this morning. I opened a new notebook and run it on next.juliabox.com.

All folders and notebooks, except for tutorial and what's new on juliabox.com this afternoon when I tried to retrieve some files from juliabox.com.

The email I used for both is merlinjumbo@gmail.com.

Please look into that.

Thank you.

**Comment by nkottary** [comment]
I have restored your backup. Please retry the migrate button on next.juliabox.com. Please email us at juliabox@juliacomputing.com if you have further issues.

**Comment by yulin2017** [comment]
Problem solved. Thank you very much.
